SET FOREIGN_KEY_CHECKS = 0;
drop table seminario.cliente;
drop table seminario.permiso;
drop table seminario.permiso_rol;
drop table seminario.persona;
drop table seminario.rol;
drop table seminario.usuario;
drop table seminario.usuario_rol;
-- drop table seminario.localidad;
drop table seminario.localidad_clasificacion;
drop table seminario.viaje;
drop table seminario.vehiculo;
drop table seminario.calificacion;
drop table seminario.comision_cobrada;
drop table seminario.pasajero_viaje;
drop table seminario.localidad_viaje;
drop table seminario.maneja;
drop table beneficio;
drop table comision;
drop table cupon;
drop table movimiento_puntos;
drop table movimiento_saldo;
drop table seguidor_viaje;
drop table precio_comision;
drop table pago;
drop table sancion;
drop table sponsor;
drop table tipo_sancion;
drop table notificacion;
drop table estado_viaje;
drop table estado_comision;
drop table tipo_mov_saldo;
drop table comentario_viaje;
drop table tipo_mov_puntos;
drop table seguidor_viaje;
drop table sequence;
drop table comentario_viaje;
SET FOREIGN_KEY_CHECKS = 1; 
