SET FOREIGN_KEY_CHECKS = 0;
truncate seminario.cliente;
truncate seminario.permiso;
truncate seminario.permiso_rol;
truncate seminario.persona;
truncate seminario.rol;
truncate seminario.usuario;
truncate seminario.usuario_rol;
truncate seminario.localidad_clasificacion;
truncate seminario.viaje;
truncate seminario.vehiculo;
truncate seminario.calificacion;
truncate seminario.comision_cobrada;
truncate seminario.pasajero_viaje;
truncate seminario.localidad_viaje;
truncate seminario.maneja;
truncate seminario.estado_viaje;
truncate seminario.comentario_viaje;
SET FOREIGN_KEY_CHECKS = 1; 
